### ISSUE TITLE
Some code of Processor Engine, not logging the stacktrace of Exception

### ISSUE THREAD

**Issue by kharal5** [NLP4L/framework#83]
I see some of the code in ProcessorChain logging only exception message.
`
      case e: Exception => logger.error(e.getMessage)
`
This code logs only the following one line in case of NullPointerException.
`- org.nlp4l.framework.processors.ProcessorChainBuilder - null
`
As a result, I can not see what's happening in my processor.

I'd like to see exception stacktraces in this case.
I think any exception log shoud also output Exception itself
like the following
`      case e: Exception => logger.error(e.getMessage, e)
`
so that we can see the stacktrace like the following.
```
- org.nlp4l.framework.processors.ProcessorChainBuilder - null
java.lang.NullPointerException: null
	at opennlp.tools.util.model.BaseModel.getManifestProperty(BaseModel.java:491) ~[opennlp-tools-1.5.3.jar:1.5.3]
	at opennlp.tools.util.model.BaseModel.initializeFactory(BaseModel.java:245) ~[opennlp-tools-1.5.3.jar:1.5.3]
	at opennlp.tools.util.model.BaseModel.loadModel(BaseModel.java:237) ~[opennlp-tools-1.5.3.jar:1.5.3]
	at opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:181) ~[opennlp-tools-1.5.3.jar:1.5.3]
	at opennlp.tools.sentdetect.SentenceModel.<init>(SentenceModel.java:95) ~[opennlp-tools-1.5.3.jar:1.5.3]
	at org.nlp4l.nee.OpenNLPNeeRecordProcessor.<init>(OpenNLPNeeExtractionProcessor.scala:79) ~[nlp4l_2.11-0.2-dev.jar:0.2-dev]
	at org.nlp4l.nee.OpenNLPNeeRecordProcessorFactory.getInstance(OpenNLPNeeExtractionProcessor.scala:51) ~[nlp4l_2.11-0.2-dev.jar:0.2-dev]
	at org.nlp4l.framework.processors.ProcessorChainBuilder.wrapBuild(ProcessorChain.scala:334) [classes/:na]
	at org.nlp4l.framework.processors.ProcessorChainBuilder$$anonfun$procBuild$1.apply(ProcessorChain.scala:286) [classes/:na]
	at org.nlp4l.framework.processors.ProcessorChainBuilder$$anonfun$procBuild$1.apply(ProcessorChain.scala:283) [classes/:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:750) [scala-library-2.11.6.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202) [scala-library-2.11.6.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [scala-library-2.11.6.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [scala-library-2.11.6.jar:na]
	at org.nlp4l.framework.processors.ProcessorChainBuilder.procBuild(ProcessorChain.scala:282) [classes/:na]
	at org.nlp4l.framework.processors.ProcessorChain$.getChain(ProcessorChain.scala:165) [classes/:na]
	at org.nlp4l.framework.actors.ProcessorChainActor$$anonfun$receive$1.applyOrElse(ProcessorChainActor.scala:32) [classes/:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [akka-actor_2.11.jar:na]
	at org.nlp4l.framework.actors.ProcessorChainActor.aroundReceive(ProcessorChainActor.scala:28) [classes/:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]

```

**Comment by kojisekig** [comment]
This is trivial to resolve. Please fix them.

**Comment by kharal5** [comment]
In addition to this, WrapProcessor doesn't seem to terminate properly in some case of exception.
(JobStatus stays as Running.)

Probably, we also need to add throw(e)
```
case e: Exception => logger.error(e.getMessage, e) 
throw(e)
```

I will handle it, too.

**Comment by kharal5** [comment]
Throwing exception seems to be necessary, 
but the reason of "not terminate properly" doesn't seem to be related.
Probably, a kind of job configuration mistake could cause it ?
I can' t reproduce it for now. we will see for a while.

**Comment by kharal5** [comment]
I have changed the source and commited. Now you can see the stacktrace, too.
